### ISSUE TITLE
Additional Pages for generating PR's and Issues

### ISSUE THREAD

**Issue by A1Liu** [BUGS-NYU/bugs-nyu.github.io-old#102]
I think we should add a page that generates PR's using query parameters (or maybe edit the connect page?). So, for example, the form might have 3 fields, *title*, *date*, and *content*. Then, when the form submission button is pressed, a javascript function `onsubmit()` is called which takes the data and passes it as a query parameter to the PR link. So this form submission:

```
title: My Title
date: 2019-01-16
body: my text here
```

is sent through the URL as `?title=My%20Title&body=---%0D%0Atitle%3A+My+Title%0D%0A----%0D%0Amy+text+here` or at least something like it. It might take a while to iron out, but I think that it'd be nice to have the formatting of most of the stuff handled by Javascript.

**Comment by Kn99HN** [comment]
I believe this can be done via GitHub API. The user will probably need to have a GitHub account or make one thou

**Comment by Kn99HN** [comment]
I think this might not be as relevant anymore as we want to encourage interacting directly with the codebase
