### ISSUE TITLE
Include Bugs Email Link

### ISSUE THREAD

**Issue by esilverm** [BUGS-NYU/bugs-nyu.github.io-old#112]
There is no way to join from the website.

**Comment by A1Liu** [comment]
It's been updated to http://bit.ly/bugsnewsletter, and I'll add it to the website probably by this friday along with some other nonvisual changes

**Comment by esilverm** [comment]
I think it could fit on the connect page

**Comment by A1Liu** [comment]
Yeah lol I'll add it along with a few other changes to the page like probably during tomorrow's workshop.
