### ISSUE TITLE
Alumni Descriptions

### ISSUE THREAD

**Issue by esilverm** [BUGS-NYU/bugs-nyu.github.io-old#121]
Very minor issue, but the descriptions for the founding members are out of date and in David Klein's case, somewhat unreadable.

**Comment by A1Liu** [comment]
@KEYS248 @cr4zyafrican @anandithaaa I don't want to alter your alumni descriptions past very simple stuff. Also, I probs should have read them more closely lol 😁

**Comment by A1Liu** [comment]
@esilverm I think we can close this for now; beyond grammatical correctness I don't think there's anything I can do, and in general the onus is on the person being described to ensure that the content of their bio is correct (by opening an issue or contacting me/BUGS)
