### ISSUE TITLE
Creative Suggestions

### ISSUE THREAD

**Issue by xc4297** [BUGS-NYU/bugs-nyu.github.io-old#128]
1. What about replacing the BUGS logo on our homepage with a gif version? This [one]( https://drive.google.com/file/d/1bw100IZblkvmGL-4W7ICMLLAAqOUx2ji/view?usp=sharing) in our Drive can be a good one. 

2. I reviewed the current [template](https://github.com/BUGS-NYU/bugs-nyu.github.io/blob/master/_events/.template_event.md) for events and I found that there's no way to add any images to the event posting. Can be make that an option?

**Comment by A1Liu** [comment]
1. I completely agree - I think in general we should probably start replacing the huge image files we currently use with smaller icons; currently the assets we use are just way too large for what they do. If you'd like to do it, I think the change needs to be done in `_includes/navbutton.html`, but if not I can get it done after I finish integrating Bootstrap.

2. Images can be made in markdown with the following format:
    ```markdown
    ![alt-text](https://example.com/url/to/source/image.jpg)
    ```

    You can also insert a raw HTML `img` tag if you need more customization (size, dimensions, etc).
     I'm not sure if we should add any more support than that though; I don't want the system to become too complicated. I'll think about it some more and try to figure out a way to make event pages customizable without making it too hard to design them (maybe wordpress-esque?)
