### ISSUE TITLE
Page for Contributors

### ISSUE THREAD

**Issue by A1Liu** [BUGS-NYU/bugs-nyu.github.io-old#152]
We don't display all contributors! We definitely should have a page that shows who's contributed to the website or the club in general.

**Proposal**
A new page on the website, dedicated to people that have contributed to the website.

**Downsides and Alternatives**
It'll increase complexity of the webiste, and make it harder to maintain, but I think it's worth giving our contributors credit.

**Comment by Kn99HN** [comment]
Or we can use [all contributors](https://github.com/all-contributors/all-contributors) and display on the repo itself?

**Comment by Kn99HN** [comment]
This is addressed with #155
