### ISSUE TITLE
Adding a new Page for other NYU CS resources

### ISSUE THREAD

**Issue by Kn99HN** [BUGS-NYU/bugs-nyu.github.io-old#176]
We would like to add another page to direct students to other NYU CS club and resources available. Often times, it's difficult to find these resources without having someone telling you so it would be great if we can include other clubs, such as Tech@NYU, Winc, and resources such as opportunities mailing list, blog post such as Torch

**Comment by yuchenliu15** [comment]
something like this? [https://pittcs.wiki/](https://pittcs.wiki/)

**Comment by Kn99HN** [comment]
Yeah this looks great! I think it might be a lot to put into the same codebase or site as the club's website. Maybe it can be a separate repo and application?

**Comment by yuchenliu15** [comment]
Yea a standalone CS resources project would be really cool to work on!

**Comment by Kn99HN** [comment]
I'll close this issue in favor of a new website. Please create a repo and start a basic setup and let's start working on this : )
