### ISSUE TITLE
Embed the Mailing List Form

### ISSUE THREAD

**Issue by yuchenliu15** [BUGS-NYU/bugs-nyu.github.io-old#193]
I thought the pop up Mailchimp form for the "Join Us" tab is less convenient. Maybe embed the Mailchimp would make more sense? I can work on this if possible.
![image](https://user-images.githubusercontent.com/43976449/106372079-dba41900-6320-11eb-8982-841061fd4a07.png)

**Comment by Kn99HN** [comment]
That would be great. Feel free to open PR whenever!

**Comment by esilverm** [comment]
This seems like a good start: https://mailchimp.com/help/host-your-own-signup-forms/

**Comment by Kn99HN** [comment]
~~While on this issue, can we also find a new svg for the mail? The current one is bit pixelated and doesn't look good~~

**Comment by Kn99HN** [comment]
@yuchenliu15 can you look into this?

**Comment by yuchenliu15** [comment]
@Kn99HN yee
