### ISSUE TITLE
Contributor list

### ISSUE THREAD

**Issue by yuchenliu15** [BUGS-NYU/bugs-nyu.github.io-old#203]
I just thought that the current contributor list doesn't look that great and we have to manually update it every time.

Maybe have a svg like this?

![image](https://user-images.githubusercontent.com/43976449/109378488-d686ab00-7887-11eb-8c9f-069ff2f12f07.png)

**Comment by Kn99HN** [comment]
I can't recall why I did it originally lol. But this looks a lot better. Do you want to take this issue?

**Comment by yuchenliu15** [comment]
@Kn99HN yea I'll do it!
