### ISSUE TITLE
NavBar Text is not highlighted upon refresh

### ISSUE THREAD

**Issue by Kn99HN** [BUGS-NYU/bugs-nyu.github.io-old#208]
<img width="1439" alt="Screen Shot 2021-03-06 at 8 47 06 PM" src="https://user-images.githubusercontent.com/44149581/110226431-32bb8180-7ebd-11eb-95a5-66865a48b3f2.png">

**Comment by Kn99HN** [comment]
~~For some reason I think #206 fixes this after removing the footer???~~

Nvm still a bug

**Comment by esilverm** [comment]
This is implemented with Gatsby's built-in Link component's `activeClassName` prop so it is likely a bug within Gatsby

See: https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/#add-custom-styles-for-the-currently-active-link

**Comment by esilverm** [comment]
Solution seems to be adding the prop `partiallyActive={true} ` to the gatsby link tags

**Comment by yuchenliu15** [comment]
hmm it works fine for me

how to reproduce this bug?

**Comment by Kn99HN** [comment]
This happens on Safari and Firefox for me. Are you using Chrome?

**Comment by yuchenliu15** [comment]
nah I use firefox, interesting...

**Comment by Kn99HN** [comment]
Huh, interesting....
