### ISSUE TITLE
Title Change

### ISSUE THREAD

**Issue by Kn99HN** [BUGS-NYU/bugs-nyu.github.io-old#213]
Webmaster sounds a bit silly (no offense to original founder) but let's change Webmaster -> Full Stack Engineer since that fits more with the roles description.

**Comment by yuchenliu15** [comment]
@Kn99HN haha I agree. what do u think about "Full Stack developer" or just "developer"?

**Comment by Kn99HN** [comment]
Full Stack Developer sounds good!
