### ISSUE TITLE
Need consistent icons

### ISSUE THREAD

**Issue by yuchenliu15** [BUGS-NYU/bugs-nyu.github.io-old#222]
#### Current Behavior

![image](https://user-images.githubusercontent.com/43976449/116642347-79f54a00-a923-11eb-95c6-4c09018a5d8e.png)

#### Desired Behavior

I think Khanh has mentioned this before. We need consistent + good looking icons :fire: :fire:

**Comment by SJellen** [comment]
what do you think of this? 

<img width="386" alt="Screen Shot 2021-04-30 at 2 09 05 PM" src="https://user-images.githubusercontent.com/51421669/116736697-3c91ca80-a9be-11eb-8d01-5c44fd2d7516.png">
<img width="386" alt="Screen Shot 2021-04-30 at 2 09 38 PM" src="https://user-images.githubusercontent.com/51421669/116736698-3c91ca80-a9be-11eb-94f4-0b1d3e2443a5.png">


I replaced the black bordered svg file with a none bordered mail svg. 

I'm sending a PR.

**Comment by yuchenliu15** [comment]
@SJellen this looks great!
