### ISSUE TITLE
Remove Graduating Eboard members

### ISSUE THREAD

**Issue by Kn99HN** [BUGS-NYU/bugs-nyu.github.io-old#227]
#### Desired Behavior

- Remove Albert, Joanna, Eric and Edmond from Eboard page

#### Mockups

---

**[Contributor Guide](https://github.com/BUGS-NYU/bugs-nyu.github.io/blob/master/contribution/CONTRIBUTING.md)**

**Comment by Ajinkya-Sonawane** [comment]
Working on the issue - Removing data as required on local repo.
