### ISSUE TITLE
link to Mozilla site

### ISSUE THREAD

**Issue by joannakl** [BUGS-NYU/bugs-nyu.github.io-old#3]
The link to Mozilla campus club page leads to the wrong site. 
I am not sure where the new site is, but we need to find out and change it.

**Comment by sinAshish** [comment]
![mozilla bug](https://user-images.githubusercontent.com/21974209/31437385-b8c21530-aea2-11e7-8409-ad91d31e1073.PNG)
Isn't this the correct site? It seems to be.

**Comment by joannakl** [comment]
sinAshish - that is exactly the problem: it looks like the correct site, but it is not. It may be that the site that I am talking about is not live yet and we were just given a preview of it.

**Comment by anandithaaa** [comment]
I'll email Christos to follow up & get the correct link. Thanks Joanna!

**Comment by joannakl** [comment]
PR https://github.com/BUGS-NYU/bugs-nyu.github.io/pull/12

**Comment by joannakl** [comment]
The previous change was only made to the site homepage. It needs to be added to all of the pages. 
Why is the menu to the same on all pages?

**Comment by KEYS248** [comment]
old issue has been fixed
