### ISSUE TITLE
Link missing from Open Data Week Page

### ISSUE THREAD

**Issue by JimenezJC** [BUGS-NYU/bugs-nyu.github.io-old#31]
Under "Event Details" where registration information is given, the "complete this form" link is missing. Students need this link in order to get the registration password for the event. 

![open](https://user-images.githubusercontent.com/17581970/36358584-b86f47d6-14de-11e8-90af-919714b70d53.png)

**Comment by JimenezJC** [comment]
The issue is a missing href source for this line.
https://github.com/BUGS-NYU/bugs-nyu.github.io/blob/master/open-data/open_data_week.html#L45

**Comment by S1MB10T3** [comment]
The link should be [https://goo.gl/forms/jGNMekxQ52ucYwbz1](https://goo.gl/forms/jGNMekxQ52ucYwbz1)

**Comment by KEYS248** [comment]
event is over, link no longer relevant
