### ISSUE TITLE
BUGS office?

### ISSUE THREAD

**Issue by joannakl** [BUGS-NYU/bugs-nyu.github.io-old#4]
The website lists BUGS office as:

BUGS NYU.
Warren Weaver Hall, Room 423 
New York, NY 10003

This is not accurate!

**Comment by sinAshish** [comment]
then what is the correct address? i don't really understand this issue.

**Comment by joannakl** [comment]
sinAshish: thanks for our interest. I am afraid, though, that this has to be decided first in some internal discussions of the club.
