### ISSUE TITLE
automatic updating of home page "important" banner

### ISSUE THREAD

**Issue by KEYS248** [BUGS-NYU/bugs-nyu.github.io-old#42]
It'd be nice if the banner on the home page could
- [x] automatically display events on banner
- [x] update "important" script to display latest event instead of first event
- [x] add time and location of event (may require adding variables in events)
- [x] display a short summary or excerpt of the next calendar event (similar to the new posts)
- [x] remain empty if there are no future events
- [x] and stop relying on us having to update the "important.html" file each time

**Comment by S1MB10T3** [comment]
I agree with these enhancements. Found an question on stack-overflow with the solution to updating the `important.html` file [https://stackoverflow.com/questions/17890493/how-can-i-show-just-the-most-recent-post-on-my-home-page-with-jekyll?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa](https://stackoverflow.com/questions/17890493/how-can-i-show-just-the-most-recent-post-on-my-home-page-with-jekyll?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

But it would be nice to have a way to get the first "important" or "featured" event on the banners. Probably need create a boolean tag for the events and then work from there.

**Comment by KEYS248** [comment]
Pull request #60 has successfully automated the banner, issue done!
