### ISSUE TITLE
README and CONTRIBUTE formatting

### ISSUE THREAD

**Issue by A1Liu** [BUGS-NYU/bugs-nyu.github.io-old#70]
Hi! I think that the CONTRIBUTE.md file should describe the process for installing and using Jekyll, as opposed to just pushing commits to a fork and loading the github pages site. 

Maybe the README.md page should link to CONTRIBUTE.md for a guide on how to contribute, and then move the jekyll guide to CONTRIBUTE.md instead?

**Comment by joannakl** [comment]
I agree that the Jekyll instructions should be part of the CONTRIBUTE document. 
But I would not remove the instructions for the process of testing the site with just a github pages site setup. For some potential contributors, it is a much simpler setup that does not require the installation of new packages.  It also allows us the verify that the site is still functional after the proposed changes.
