### ISSUE TITLE
The eboard members should be in a collection

### ISSUE THREAD

**Issue by A1Liu** [BUGS-NYU/bugs-nyu.github.io-old#76]
For easier maintenance and readability, the eboard members should be listed in a collection, not in raw HTML

**Comment by joannakl** [comment]
agreed! 
this will require 
1) changes to the current HTML
2) instructions somewhere in that code (or README file) for how the new members should be added/removed

**Comment by A1Liu** [comment]
The HTML in `about.html` should be basically good to go; I don't know what to do about the "founding members" or "mentor" sections, but they could probably be implemented in the eboard collection, and then the order could be determined with some kind of meta-attribute.
