### ISSUE TITLE
baseurl shouldn't be used for absolute URL

### ISSUE THREAD

**Issue by A1Liu** [BUGS-NYU/bugs-nyu.github.io-old#78]
`site.baseurl` (or `baseurl` in the config file) should not contain the domain "bugs-nyu.github.io" - instead, this information should be held in `site.url`.

The problem is that testing the site locally requires first removing the baseurl from the file, and then reappending it after testing is done.

**Comment by joannakl** [comment]
I agree with this on a hypothetical level. 
But I believe that in the past using site.url by itself resulted in some problems. 
This should be tested carefully before it is actually approved as a change.

**Comment by A1Liu** [comment]
@joannakl So I think the reason why is because when you fork the repository, the baseurl becomes `bugs-nyu.github.io/` and the actual url becomes `https://username.github.io`; when the website's live it probably works fine, but while testing from github pages it doesn't work. I don't know what the best way to fix this would be, but I think it might be solvable by setting `baseurl` to `/bugs-nyu.github.io` when forking (remove the https://). Ideally though, baseurl should only be set to a non-empty value when it's being forked, and the links as relative links instead of absolute links

**Comment by A1Liu** [comment]
it looks like this already has been implemented by accident, without removing any of the baseurl liquid tags. I think this is ultimately the best route; for testing purposes some people might want to use github pages to view their fork of the website, and the baseurl is crucial to make that work properly.
